// packages/vitx-site/template/react/desktopMain.jsx
import { documentsDetails, config, documents, utils } from '@vitx-documents-desktop'
import { Route, Routes, BrowserRouter, Navigate } from 'react-router-dom'
import React, { Suspense, Fragment } from 'react'
import BuiltSite from 'vitx-site-common/element'
import { render } from 'react-dom'
import 'vitx-site-common/styles'

function App() {
  const {
    site: { lazy: isLazy, defaultLang }
  } = config
  const { parseName } = utils

  const otherRoute = []
  const componentsRoute = []
  const meta = {}

  const RootElement = isLazy ? Suspense : Fragment
  const RootElementProps = isLazy ? { fallback: <Fragment /> } : {}

  let homePath = ''

  documentsDetails.forEach((item) => {
    const { component, lang } = parseName(item.name)
    const Element = documents[item.name]

    if (component === 'home' && lang === defaultLang) {
      homePath = `/${lang}/${component}`
    }

    if (item.isComponent) {
      meta[`/components/${lang}/${component}`] = lang
      componentsRoute.push(<Route key={name} path={`${lang}/${component}`} element={<Element />} />)
    } else {
      otherRoute.push(
        <Route key={item.name} path={`/${lang}/${component}`} element={<Element />} />
      )
    }
  })

  return (
    <RootElement {...RootElementProps}>
      <BrowserRouter>
        <Routes>
          {otherRoute}
          <Route
            path="/components"
            element={<BuiltSite config={config} key="builsite" meta={meta} />}
          >
            {componentsRoute}
          </Route>
          <Route path="*" element={<Navigate to={homePath} replace />} />
        </Routes>
      </BrowserRouter>
    </RootElement>
  )
}

render(<App />, document.getElementById('vitx-app'))

// packages/vitx-site/template/vue/desktopMain.jsx
import { documents, config, documentsDetails, utils } from '@vitx-documents-desktop'
import { createRouter, createWebHistory } from 'vue-router'
import BuiltSite from 'vitx-site-common/element'
import 'vitx-site-common/styles'
import { createApp } from 'vue'

function Components() {
  return (
    <BuiltSite config={config}>
      <router-view />
    </BuiltSite>
  )
}

function installRouters() {
  /** @type {{path:string, name:string}[]} */
  const docs = documents
  const routes = []
  const { locales } = config.site
  const { parseName } = utils

  const componentsRoute = {
    path: '/components',
    component: Components,
    children: []
  }

  routes.push({
    name: 'notFound',
    path: '/:path(.*)+',
    redirect: {
      name: 'home'
    }
  })

  if (locales) {
    documentsDetails.forEach(({ name, isComponent }) => {
      const { component, lang } = parseName(name)

      if (isComponent) {
        componentsRoute.children.push({
          name,
          path: `${lang}/${component}`,
          component: docs[name],
          meta: { lang, name: component }
        })
      } else {
        routes.push({
          name,
          path: `/${lang}/${component}`,
          component: docs[name],
          meta: {
            lang,
            name: component
          }
        })
      }
    })
  } else {
    documentsDetails.forEach(({ name, isComponent }) => {
      if (isComponent) {
        componentsRoute.children.push({
          name,
          path: name,
          component: docs[name],
          meta: { name }
        })
      } else {
        routes.push({
          name: `${name}`,
          path: `/${name}`,
          component: docs[name],
          meta: {
            name
          }
        })
      }
    })
  }

  routes.push(componentsRoute)

  return routes
}

const routers = createRouter({
  history: createWebHistory(),
  routes: installRouters()
})

function App() {
  return <router-view />
}

createApp(App).use(routers).mount('#vitx-app')
